#!D:\Winpython\basedir27\build\winpython-2.7.10.amd64\python-2.7.10.amd64\python.exe

import warnings
warnings.simplefilter('default', DeprecationWarning)

from logilab.common.pytest import run
run()
